apiVersion: v1
kind: PersistentVolume 
metadata:
  name: els1-pv
spec:
  capacity:
    storage: 25Gi
  volumeMode: Filesystem 
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local: 
    path: "/opt/elasticsearch1"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname 
          operator: In 
          values:
          - kworker1
---
apiVersion: v1
kind: PersistentVolume 
metadata:
  name: els2-pv
spec:
  capacity:
    storage: 25Gi
  volumeMode: Filesystem 
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local: 
    path: "/opt/elasticsearch2"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname 
          operator: In 
          values:
          - kworker2
---
kind: StorageClass 
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
